
package com.example.world.dao.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InMemoryWorldDaoService", targetNamespace = "http://impl.dao.world.example.com/", wsdlLocation = "file:/C:/temp/InMemoryWorldDaoService.wsdl")
public class InMemoryWorldDaoService
    extends Service
{

    private final static URL INMEMORYWORLDDAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException INMEMORYWORLDDAOSERVICE_EXCEPTION;
    private final static QName INMEMORYWORLDDAOSERVICE_QNAME = new QName("http://impl.dao.world.example.com/", "InMemoryWorldDaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/temp/InMemoryWorldDaoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INMEMORYWORLDDAOSERVICE_WSDL_LOCATION = url;
        INMEMORYWORLDDAOSERVICE_EXCEPTION = e;
    }

    public InMemoryWorldDaoService() {
        super(__getWsdlLocation(), INMEMORYWORLDDAOSERVICE_QNAME);
    }

    public InMemoryWorldDaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INMEMORYWORLDDAOSERVICE_QNAME, features);
    }

    public InMemoryWorldDaoService(URL wsdlLocation) {
        super(wsdlLocation, INMEMORYWORLDDAOSERVICE_QNAME);
    }

    public InMemoryWorldDaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INMEMORYWORLDDAOSERVICE_QNAME, features);
    }

    public InMemoryWorldDaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InMemoryWorldDaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InMemoryWorldDao
     */
    @WebEndpoint(name = "InMemoryWorldDaoPort")
    public InMemoryWorldDao getInMemoryWorldDaoPort() {
        return super.getPort(new QName("http://impl.dao.world.example.com/", "InMemoryWorldDaoPort"), InMemoryWorldDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InMemoryWorldDao
     */
    @WebEndpoint(name = "InMemoryWorldDaoPort")
    public InMemoryWorldDao getInMemoryWorldDaoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.dao.world.example.com/", "InMemoryWorldDaoPort"), InMemoryWorldDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INMEMORYWORLDDAOSERVICE_EXCEPTION!= null) {
            throw INMEMORYWORLDDAOSERVICE_EXCEPTION;
        }
        return INMEMORYWORLDDAOSERVICE_WSDL_LOCATION;
    }

}
