
package com.example.world.dao.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.example.world.dao.City;
import com.example.world.dao.Country;
import com.example.world.dao.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorldDao", targetNamespace = "http://dao.world.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorldDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.example.world.dao.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCitiesByCountryCode", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCitiesByCountryCode")
    @ResponseWrapper(localName = "findCitiesByCountryCodeResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCitiesByCountryCodeResponse")
    public List<City> findCitiesByCountryCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.world.dao.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCountries", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindAllCountries")
    @ResponseWrapper(localName = "findAllCountriesResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindAllCountriesResponse")
    public List<Country> findAllCountries();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCountryByCode", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCountryByCode")
    @ResponseWrapper(localName = "findCountryByCodeResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCountryByCodeResponse")
    public Country findCountryByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllContinents", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.GetAllContinents")
    @ResponseWrapper(localName = "getAllContinentsResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.GetAllContinentsResponse")
    public List<String> getAllContinents();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCity", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.RemoveCity")
    @ResponseWrapper(localName = "removeCityResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.RemoveCityResponse")
    public City removeCity(
        @WebParam(name = "arg0", targetNamespace = "")
        City arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCity", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.UpdateCity")
    @ResponseWrapper(localName = "updateCityResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.UpdateCityResponse")
    public City updateCity(
        @WebParam(name = "arg0", targetNamespace = "")
        City arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCountry", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.AddCountry")
    @ResponseWrapper(localName = "addCountryResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.AddCountryResponse")
    public Country addCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCityById", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCityById")
    @ResponseWrapper(localName = "findCityByIdResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCityByIdResponse")
    public City findCityById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCountry", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.UpdateCountry")
    @ResponseWrapper(localName = "updateCountryResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.UpdateCountryResponse")
    public Country updateCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.example.world.dao.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCountriesByContinent", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCountriesByContinent")
    @ResponseWrapper(localName = "findCountriesByContinentResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindCountriesByContinentResponse")
    public List<Country> findCountriesByContinent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCountry", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.RemoveCountry")
    @ResponseWrapper(localName = "removeCountryResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.RemoveCountryResponse")
    public Country removeCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.world.dao.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCities", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindAllCities")
    @ResponseWrapper(localName = "findAllCitiesResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.FindAllCitiesResponse")
    public List<City> findAllCities();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCity", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.AddCity")
    @ResponseWrapper(localName = "addCityResponse", targetNamespace = "http://dao.world.example.com/", className = "com.example.world.dao.AddCityResponse")
    public City addCity(
        @WebParam(name = "arg0", targetNamespace = "")
        City arg0);

}
