
package com.example.imdb.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InMemoryMovieServiceService", targetNamespace = "http://impl.service.imdb.example.com/", wsdlLocation = "http://localhost:8080/imdb-soap-webservice/InMemoryMovieServiceService.wsdl")
public class InMemoryMovieServiceService
    extends Service
{

    private final static URL INMEMORYMOVIESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException INMEMORYMOVIESERVICESERVICE_EXCEPTION;
    private final static QName INMEMORYMOVIESERVICESERVICE_QNAME = new QName("http://impl.service.imdb.example.com/", "InMemoryMovieServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/imdb-soap-webservice/InMemoryMovieServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INMEMORYMOVIESERVICESERVICE_WSDL_LOCATION = url;
        INMEMORYMOVIESERVICESERVICE_EXCEPTION = e;
    }

    public InMemoryMovieServiceService() {
        super(__getWsdlLocation(), INMEMORYMOVIESERVICESERVICE_QNAME);
    }

    public InMemoryMovieServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INMEMORYMOVIESERVICESERVICE_QNAME, features);
    }

    public InMemoryMovieServiceService(URL wsdlLocation) {
        super(wsdlLocation, INMEMORYMOVIESERVICESERVICE_QNAME);
    }

    public InMemoryMovieServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INMEMORYMOVIESERVICESERVICE_QNAME, features);
    }

    public InMemoryMovieServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InMemoryMovieServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InMemoryMovieService
     */
    @WebEndpoint(name = "InMemoryMovieServicePort")
    public InMemoryMovieService getInMemoryMovieServicePort() {
        return super.getPort(new QName("http://impl.service.imdb.example.com/", "InMemoryMovieServicePort"), InMemoryMovieService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InMemoryMovieService
     */
    @WebEndpoint(name = "InMemoryMovieServicePort")
    public InMemoryMovieService getInMemoryMovieServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.imdb.example.com/", "InMemoryMovieServicePort"), InMemoryMovieService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INMEMORYMOVIESERVICESERVICE_EXCEPTION!= null) {
            throw INMEMORYMOVIESERVICESERVICE_EXCEPTION;
        }
        return INMEMORYMOVIESERVICESERVICE_WSDL_LOCATION;
    }

}
