
package com.example.world.dao.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InMemoryWorldDao", targetNamespace = "http://impl.dao.world.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InMemoryWorldDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCity", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.RemoveCity")
    @ResponseWrapper(localName = "removeCityResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.RemoveCityResponse")
    public City removeCity(
        @WebParam(name = "arg0", targetNamespace = "")
        City arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCities1", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities1")
    @ResponseWrapper(localName = "createCities1Response", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities1Response")
    public void createCities1();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllContinents", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.GetAllContinents")
    @ResponseWrapper(localName = "getAllContinentsResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.GetAllContinentsResponse")
    public List<String> getAllContinents();

    /**
     * 
     * @return
     *     returns java.util.List<com.example.world.dao.impl.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCountries", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindAllCountries")
    @ResponseWrapper(localName = "findAllCountriesResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindAllCountriesResponse")
    public List<Country> findAllCountries();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCountries", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCountries")
    @ResponseWrapper(localName = "createCountriesResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCountriesResponse")
    public void createCountries();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.example.world.dao.impl.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCitiesByCountryCode", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCitiesByCountryCode")
    @ResponseWrapper(localName = "findCitiesByCountryCodeResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCitiesByCountryCodeResponse")
    public List<City> findCitiesByCountryCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCountryByCode", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCountryByCode")
    @ResponseWrapper(localName = "findCountryByCodeResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCountryByCodeResponse")
    public Country findCountryByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.world.dao.impl.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCities", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindAllCities")
    @ResponseWrapper(localName = "findAllCitiesResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindAllCitiesResponse")
    public List<City> findAllCities();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCities2500", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities2500")
    @ResponseWrapper(localName = "createCities2500Response", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities2500Response")
    public void createCities2500();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.example.world.dao.impl.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCountriesByContinent", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCountriesByContinent")
    @ResponseWrapper(localName = "findCountriesByContinentResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCountriesByContinentResponse")
    public List<Country> findCountriesByContinent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCountry", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.RemoveCountry")
    @ResponseWrapper(localName = "removeCountryResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.RemoveCountryResponse")
    public Country removeCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCities3600", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities3600")
    @ResponseWrapper(localName = "createCities3600Response", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities3600Response")
    public void createCities3600();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCity", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.AddCity")
    @ResponseWrapper(localName = "addCityResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.AddCityResponse")
    public City addCity(
        @WebParam(name = "arg0", targetNamespace = "")
        City arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCountry", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.AddCountry")
    @ResponseWrapper(localName = "addCountryResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.AddCountryResponse")
    public Country addCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCityById", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCityById")
    @ResponseWrapper(localName = "findCityByIdResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.FindCityByIdResponse")
    public City findCityById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.InitResponse")
    public void init();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCountry", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.UpdateCountry")
    @ResponseWrapper(localName = "updateCountryResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.UpdateCountryResponse")
    public Country updateCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCities2000", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities2000")
    @ResponseWrapper(localName = "createCities2000Response", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities2000Response")
    public void createCities2000();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.world.dao.impl.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCity", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.UpdateCity")
    @ResponseWrapper(localName = "updateCityResponse", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.UpdateCityResponse")
    public City updateCity(
        @WebParam(name = "arg0", targetNamespace = "")
        City arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCities1000", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities1000")
    @ResponseWrapper(localName = "createCities1000Response", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities1000Response")
    public void createCities1000();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createCities3000", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities3000")
    @ResponseWrapper(localName = "createCities3000Response", targetNamespace = "http://impl.dao.world.example.com/", className = "com.example.world.dao.impl.CreateCities3000Response")
    public void createCities3000();

}
